name: Reset branch to specific commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit-SHA, zu dem zurückgesetzt werden soll"
        required: true
        type: string
      branch:
        description: "Branch, der zurückgesetzt werden soll"
        required: true
        default: "main"
        type: string

permissions:
  contents: write

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin
          git checkout ${{ inputs.branch }}
          git reset --hard ${{ inputs.commit_sha }}
          git push origin ${{ inputs.branch }} --force
